### ISSUE TITLE
Consider renaming command names

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/victor-cli#12]
Typing `to-ruby` and `to-svg` is no fun.

How about
- `victor import` - to import SVG and convert it to Victor Ruby
- `victor render` - to render Victor Ruby to SVG

@gingermusketeer thoughts?

**Comment by gingermusketeer** [comment]
`import` feels like the wrong term, to me it suggests that the file is going to added to a DB. Throwing a few ideas out: `victorize`, `convert`, `codify`. 

Another thought is that can we simply detect the file type and decide what to do based on that. If the file is an SVG then there is no other possibility then converting it to ruby.

**Comment by DannyBen** [comment]
Joining the two commands and "auto detect" is a nice idea, but it will cause other issues. For example, it will make that single command more complex, and force it to handle two different cases. In addition, the arguments are already different (`--template` needs a different set of values) and may differ more in the future.

I am not a fan of invented words like `victorize` and `codify`, and `convert` is suffering from the same problem as did `generate` before - convert what to what? 

Isn't it exactly like you import a CSV to a Google Sheet?
You import "the other format" (SVG) to the native syntax of said app (Victor), which is a "victor flavored ruby script".

**Comment by gingermusketeer** [comment]
Arguments against magic detection are pretty understandable. Make it much harder to maintain.

I think spreadsheets are a kind of database and it doesn't feel like this is dealing with data in that manner. To me the tool is more like compiling c into machine code. Taking one representation of a a program and converting it into another. Perhaps this is best desired as translation? English to French, SVG to Ruby.

I think the "what to what" argument could also be applied to `import`? Import what/from to where?

If the problem is that the commands are too much to type, what about adding aliases? `tr` and `ts` for example.

**Comment by DannyBen** [comment]
> I think the "what to what" argument could also be applied to import? Import what/from to where?

Not exactly.
Since we know victor CLI can handle both SVG => Ruby and Ruby => SVG, `generate` or `convert` is confusing, because it can be applied to both actions.
The word `import` however, cannot. There should be no reason to `import` Ruby.

> If the problem is that the commands are too much to type, what about adding aliases? tr and ts for example.
Having a shortcut is not a replacement for having a descriptive, good word in the first place.

Also - I don't like the presumed symmetry in the `to-ruby` and `to-svg` - it is not symmetric.
Victor is designed to create SVG. Thats its purpose.
The `to-ruby` operation is just a step towards making it able to fulfill its purpose. Its an operation that precedes its actual, intended operation. This, by the way, is another similarity with "import" in other programs.

**Comment by DannyBen** [comment]
@gingermusketeer - if you are not convinced about the majestic beauty of the `victor import` and `victor render`, I am willing to settle for `victor convert` and `victor render`.

**Comment by gingermusketeer** [comment]
@DannyBen That sounds like a good decision :)
