### ISSUE TITLE
Add --watch to the Ruby to SVG conversion

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/victor-cli#15]
Should probably be along the lines of:

```
victor to-svg RUBY_FILE [SVG_FILE] --watch
```

and to use the [FileWatcher gem](https://github.com/filewatcher/filewatcher)

**Comment by gingermusketeer** [comment]
@DannyBen Any reason to use Filewatcher over https://github.com/guard/listen? It looks like listen is what rails uses and relies on gems which make use of gems that hook into kernel provided functionality rather than polling.

**Comment by DannyBen** [comment]
Yes. The listen doesn't work on vagrant. Only polling.

**Comment by gingermusketeer** [comment]
Ah right I had not considered that. It looks like listen has a polling adapter that can be used https://github.com/guard/listen/blob/896c74c83bdba0d1698af3828a14b28d813cad7c/README.md#options

**Comment by DannyBen** [comment]
FileWatcher is easy and simple. I had multiple issues with listen.
FileWatcher is 188 LOC against 1680 in listen. It does the job and does it well.
Is there any reason why *not* to use FileWatcher?
